baseurl = "/"
title = "Sapienza Hub"
languageCode = "it"
copyright = "My Name"

[Author]
    name = "Sapienza Students"
    profile = ""

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Sapienza Hub"
    description = "Creata dagli studenti per gli studenti"
    gitlab = "https://gitlab.com/sapienzastudents"
    telegram = "https://t.me/sapienzainformatica"
    email = "sapienzahub@gmail.com"
    opengraph = false
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "2006-01-02"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    readingTime = false
    readingTimeText = "Estimated reading time:"
    fathomUrl = ""
    fathomSiteId = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 2

[[menu.main]]
    name = "Gruppi"
    url = "/social/"
    weight = 3

[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 4

[[menu.main]]
    name = "Risorse"
    url = "/resources/"
    weight = 5

[[menu.main]]
    name = "Informazioni"
    url = "/info/"
    weight = 6

[[menu.main]]
    name = "Guide"
    url = "/howto/"
    weight = 7
    
[[menu.main]]
    name = "Chi Siamo"
    url = "/about/"
    weight = 8

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true