baseurl = "/"
title = "Sapienza Hub"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Sapienza Students"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Sapienza Hub"
    description = "Creata dagli studenti per gli studenti"
    gitlab = "https://gitlab.com/sapienzastudents"
    email = "sapienzahub@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"
    fathomUrl = ""
    fathomSiteId = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Risorse"
    url = "/resources/"
    weight = 3

[[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 1

[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 2

[[menu.main]]
    name = "Chi Siamo"
    url = "/about/"
    weight = 4
